---
title: "Homework 4: Chapter 4 of MSWR"
author: "Your Name Here"
date: "Due: Sunday, Apr 26"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, fig.align = "center", warning = FALSE, message = FALSE)
library(tidyverse)
library(resampledata)
```

&nbsp;

***

set.seed(888) for all problems

***

1. Consider the population $\{3, 6, 7, 9, 11, 14\}$.  For samples of size 3 without replacement, find (and plot) the sampling distribution of the minimum.  What is the mean of the sampling distribution?  



***

Note: For the question 2, you need to know about the Uniform distribution is. (We did not talked about this distribution in class) As far as $R$ codes go, knowing how to generate a random sample from a uniform distribution in $R$ is enough.

2.  Let $X$ be a uniform random variable on the interval $[40, 60]$ and $Y$ a uniform random variable on $[45, 80].$  Assume that $X$ and $Y$ are independent.

      a. Simulate the sampling distribution of $X + Y.$  Desribe the graph of the distribution of $X + Y$.  Compute the mean and variance of the sampling distribution using the simulation.


      b.  Suppose the time (in minutes) Jack takes to complete his statistics homework is $\text{Unif}[40, 60]$ and the time JIll takes is $\text{Unif}[45, 80].$  Assume they work independently.  One day they announce that their total time to finish an assignment was less than 90 min.  How likely is this?
      


***

3. The amount of time spouses shop for anniversary cards can be modeled by an exponential distribution with the average amount of time equal to 8 minutes. 

    a. Suppose 10 spouses are shoping for anniversary cards. Use the CLT to estimate the probability that, the ***mean** time* spent is less than 5 minutes.
    
    
    
    
    b. Use a sumulation to estimate the probability in part a)
    
    
    
***


4. Complete the *Exercise 4.5 (Page 94 of MSWR)*
      
      
***