---
title: "Tentative STT 3850 Course Schedule"
author: "Dr. Hasthika Rupasinghe"
date: 'Last compiled: `r format(Sys.time(), "%A, %B %d, %Y - %X.")`'
output:
  html_document:
    css: ../css/style.css
    highlight: textmate
    theme: yeti
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

### General Notes: {-}

```{block, note-text, type='rmdnote'}
1.  Please bring a notebook and pencil to every class.
2.  The texts for this course are [ModernDive: An Introduction to Statistical and Data Sciences via R](https://moderndive.com) (MD) and _Mathematical Statistics with Resampling and R_ (MSWR)
3.  Most but not all DataCamp assignments are due by 5:00 pm on a Friday (class does not meet on Friday)
```

#### Grading Rubric for Homework Assignments {-}

Field | Excellent (3) | Competent (2)  | Needs Work (1)
------|---------------|----------------|---------------
Statistical Understanding | Answers to questions demonstrate clear statistical understanding by comparing theoretical answers to simulated answers.  When hypotheses are tested, classical methods are compared and contrasted to randomization methods.  When confidence intervals are constructed, classical approaches are compared and contrasted with bootstrap procedures.  The scope of inferential conclusions made is appropriate for the sampling method. | Theoretical and simulated answers are computed but no discussion is present comparing and contrasting the results.  When hypotheses are tested, results for classical and randomization methods are presented but are not compared and contrasted.  When confidence intervals are constructed, classical and bootstrap approaches are computed but the results are not compared and contrasted.  The scope of inferential conclusions made is appropriate for the sampling method. | Theoretical and simulated answers are not computed correctly.  No comparison between classical and randomization approaches is present when testing hypotheses.  When confidence intervals are constructed, there is no comparison between classical and bootstrap confidence intervals .
Graphics | Graphs for categorical data (barplot, mosaic plot, etc.) have appropriately labeled axes and titles.  Graphs for quantitative data (histograms, density plots, violin plots, etc.) have appropriately labeled axes and titles.  Multivariate graphs use appropriate legends and labels.  Computer variable names are replaced with descriptive variable names. | Appropriate graphs for the type of data are used.  Not all axes have appropriate labels or computer variable names are used in the graphs. | Inappropriate graphs are used for the type of data.  Axes are not labeled and computer variable names appear in the graphs.
Coding  | Code (primarily R) produces correct answers.  Non-standard or complex functions are commented.  Code is formatted using a consistent standard. | Code produces correct answers.  Commenting is not used with non-standard and complex functions.  No consistent code formatting is used. | Code does not produce correct answers.  Code has no comments and is not formatted.
Clarity  | Few errors of grammar and usage; any minor errors do not interfere with meaning.  Language style and word choice are highly effective and enhance meaning.  Style and word choice are appropriate for the assignment. | Some errors of grammar and usage; errors do not interfere with meaning.  Language style and word choice are, for the most part, effective and appropriate for the assignment. | Major errors of grammar and usage make meaning unclear.  Language style and word choice are ineffective and/or inappropriate.


## Week 1: (Jan 13--17) {-}


* Read chapters 1 and 2 of [MD](https://moderndive.com)

* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.

* [Lecture: Intro to R](../Slides/IntroToR.html)

* _Complete Introduction to R_ [(DataCamp)](https://www.datacamp.com/) --- 

* In class **quiz 01** --- Thursday (last 20 min of class)


## Week 2: (Jan 20--24) {-}

* Read chapter 2 of [MD](https://moderndive.com) --- Data Visualization via `ggplot2`

* Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)

* [Rmarkdown Basics](../Lecture Notes/R_Markdown_Basics.html)

* [Lecture: Week 2](../Lecture Notes/Week2_Ch3MD_students.html)

* Complete _Data Visualization with `ggplot2`_ (Part 1) [(DataCamp)](https://www.datacamp.com/)

* Complete _Introduction to Data_ [(DataCamp)](https://www.datacamp.com/courses/introduction-to-data) - optional --- 

* In class **quiz 02** --- Thursday (last 20 min of class)




## Week 3 (Jan 27--Jan 31) {-}

* Read Chapter 2 of MSWR

* [Lecture - Chapter 2 of MSWR: Week 3](../Lecture Notes/Week4_Ch2MSWR_students.html)

* [Homework 1: Chapter 2 of MSWR](../Homework/Chapter2HWK.html)

* Complete _Reporting with R Markdown_ [(DataCamp)](https://www.datacamp.com/courses/reporting-with-r-markdown) ---  (optional)

*  Complete _Introduction to the Tidyverse_ [(DataCamp)](https://www.datacamp.com/courses/introduction-to-the-tidyverse) ---  (optional)


* In class **quiz 03** --- Thursday (last 20 min of class)

```{block, TEST1, type='rmdnote'}
* Prepare R Markdown `cheat sheet` for Test 1 (Written Assignment #1---5% of course grade)
* Test 1 --- Sep 19
```


```{block, week3optional, type='rmdoptional'}
#### Optional {-}


* Nice [Tidyverse Cheat Sheet](http://datacamp-community.s3.amazonaws.com/e63a8f6b-2aa3-4006-89e0-badc294b179c)
```



## Week 4: (Feb 3--7) {-}

* Read chapter 5 of [MD](https://moderndive.com) --- Data Wrangling via `dplyr`

* Read Chapter 3 of MSWR

* [Lecture: Before Chapter 3: the `for` loop in R](../Lecture Notes/Before_Ch_03_students.html)

* [Lecture: Chapter 3](../Lecture Notes/Ch-3_Notes_students.html)

* Complete Chapters 1-3 of _Intermediate R_ [(DataCamp)](https://www.datacamp.com/courses/intermediate-r) --- 

* Complete _Exploratory Data Analysis_ [(DataCamp)](https://www.datacamp.com/) --- 

* In class **quiz 04** --- Thursday (last 20 min of class)


## Week 5: (Feb 10--14) {-}

* Complete _Working with Data in the Tidyverse_ [(DataCamp)](https://www.datacamp.com/courses/working-with-data-in-the-tidyverse) --- 

* [Lecture: Chapter 3](../Lecture Notes/Ch-3_Notes_students.html)

* [Homework 2: Chapter 3 of MSWR](../Homework/Chapter3HWK_H.html) --- 

<!--
* Work on [Is this Discrimination?](../Rmarkdown/ClassAssignment.html)

* Some ideas for how to answer the [Is this Discrimination?](../Rmarkdown/discrimination.html)
-->





```{block, week5optional, type='rmdoptional'}
#### Optional {-}
* Complete _Data Manipulation in R with `dplyr`_ [(DataCamp)](https://www.datacamp.com/)
* Complete _Working with Data in the Tidyverse_ [(DataCamp)](https://www.datacamp.com/courses/working-with-data-in-the-tidyverse)
```

## Week 6: (Feb 17--21) {-}

* [Lecture: Chapter 3](../Lecture Notes/Ch-3_Notes_students.html)

* [Homework 2: Chapter 3 of MSWR](../Homework/Chapter3HWK_H.html) --- 

* Read Chapters 5 [MD](https://moderndive.com) --- Basic Regression 

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* In class **Exam 01** --- Thursday


## Week 7: (Feb 24--28) {-}

* [Exam 1 grades (Distribution)](../Exams/GradesExam1.html)

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* Read Chapters 6 [MD](https://moderndive.com) --- Basic Regression 

* Work on _Modeling with Data in Tidyverse_ [(DataCamp)](https://www.datacamp.com/) --- 

* Read through [_Misc Regression_](../Rmarkdown/MiscRegression.html)

* In class **quiz 06** --- Thursday (last 20 min of class)

```{block, week7optional, type='rmdoptional'}
#### Optional {-}
* Read Chapter 9 of MSWR
<!--* Answer the questions at the end of [_Misc Regression_](../Rmarkdown/MiscRegression.html) for extra credit (Turn in before Spring Break starts)-->
```


## Week 8: (Mar 2--6) {-}

* Read Chapters 7 of [MD](https://moderndive.com) --- Multiple Regression

* Complete _Modeling with Data in Tidyverse_ [(DataCamp)](https://www.datacamp.com/) --- 

* Review Chapters 6 and 7 of [MD](https://moderndive.com) --- Basic Regression and Multiple Regression

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* [Homework 3: Chapter 5 of MD HW](../Homework/Chapter6_Of_MD_HWK_H.html) 

* [OJUICE dataframe for homework](../Homework/data/OJUICE.Rdata) 

## Week 9: (Mar 9--13; Spring Break) {-}

## Week 10: (Mar 16--20; No class 15th) {-}

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* [gapminder tools](https://www.gapminder.org/tools/#$chart-type=bubbles)

* [An interesting video](https://www.youtube.com/watch?v=jbkSRLYSojo)

<!-- * Read Chapter 8 of [MD](https://moderndive.com) --- Sampling

* Read Chapter 4 of MSWR --- Sampling Distributions; [Problems 2, 5, 12-16](../Homework/Chapter4HWK.Rmd)

* [Sampling Distributions](../Handouts/EVuniform.html)

* [In Class Problems](../Slides/ProbabilityProblems.html)

* Complete _Foundations of Probability in R_ [(DataCamp)](https://www.datacamp.com/) --- Due March 15

* [Probability](https://alanarnholt.github.io/GeneralStatistics/rmarkdown/probability.html) -->

* Start preparing R Markdown `cheat sheet` for Test 2

* In class **quiz 07** --- Thursday (last 20 min of class)

## Week 11: (Mar 23--27) {-}

```{block, TEST2, type='rmdnote'}
* Prepare R Markdown `info sheet` for Test 2...

```

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* [**Lecture Recording (Ch 5 0f MD)** -- 03/24](https://appstate.zoom.us/rec/share/1f5XLpz2-X5IQp3L2G2HB4V7PtTYeaa81SgY-KdZyU_4frqdfv5I4Sfgv45TVadc)

* [Lecture: Chapter 6 of MD](../Lecture Notes/Ch-7_MD_Notes.html)

* [**Lecture Recording (Ch 6 0f MD --- Part 1)** -- 03/25](https://appstate.zoom.us/rec/share/w_Z8JZD5rURLSNbvskLgYekEJJ7Ueaa81XMaq6UPmEieQcDI0d_kpt8UIMWQgeLi)

* [**Lecture Recording (Ch 6 0f MD --- Part 2)** -- 03/26](https://appstate.zoom.us/rec/share/39V3MrrJ7XhJb9bJzRnES_UDAtm5aaa8hnIZ-PoNyBzUYBalXRjEq_Lh51VxHxgL)

<!--
* Bootstrap [Example](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/TheBootstrap.html)

* Start _Inference for Numerical Data_ [(DataCamp)](https://www.datacamp.com/) --- Due March 29

* [Misc `infer` Examples](../Rmarkdown/ExamplesInfer.html)

* [Inference Examples used in class](../Handouts/InferenceExamples.pdf)


-->



* In class **quiz 08** --- Thursday (last 20 min of class)

## Week 12: (Mar 30--Apr 3) {-}

* [Lecture: Chapter 6 of MD](../Lecture Notes/Ch-7_MD_Notes.html)

* [**Lecture Recording (Ch 6 0f MD --- Part 3)** -- 03/31](https://appstate.zoom.us/rec/share/78ttIvbT0F9LT6_W0kXkZpV-QJ36X6a80SAd8vpemEpo4iO2k9x1YXzIfabp3cu5)

* [**Lecture Recording (Ch 6 0f MD --- Part 4)** -- 04/01](https://appstate.zoom.us/rec/share/1cdVEZ_R2kBJTZWVxW_vBZx7T5jUX6a81SEa8vBZys0qYJtrx-lpCKzNRoP91mI)

* [**Lecture Recording (Ch 6 0f MD --- Part 5)** -- 04/02](https://appstate.zoom.us/rec/share/tMBRMendzFpLfq_ysG6DHYcvPa7BX6a81iRN8_pfnk3iig0lDAkZCy6EqF43frHG)

* [Homework 4: Chapter 6 of MD HW](../Homework/Chapter7HWKnew.html) 
* [Homework 4: Chapter 6 of MD HW txt file](../Homework/HW4_ONLINE.txt) 


* [Multiple Linear Regression mini-project --- OPTIONAL](../Lecture Notes/MLR_Project.html)

* [`EXECSAL2.txt` dataframe for the mini-project](../Lecture Notes/EXECSAL2.txt) 


<!--
* Read Chapter 10 of [MD](https://moderndive.com) --- Hypothesis Testing

* Complete _Inference for Numerical Data_ [(DataCamp)](https://www.datacamp.com/) --- 
-->




## Week 13: (Apr 6--10) {-}


* Read Chapter 8 of MD

* Read Chapter 4 of MSWR

* [Lecture: Sampling Distributions](../Lecture Notes/Ch-4_MSWR_Notes.html)

* [**Lecture Recording (Ch 4 0f MSWR --- Part 1)** -- 04/07](https://appstate.zoom.us/rec/share/3vxzA7fI-m5LX6PUtVrcc_Z6G5v6T6a823MfqfBcnh0oO4WRwYf2rLjVqfjAqo96)


* [**Exam 2 review Recording**](https://appstate.zoom.us/rec/share/-9dwFr7-3TlLfYnf422Oc4EbB6_AX6a803dKq_AImhp8c9wQoT_szB5cTMEc5SJP)

* [Exam 2 review with answers](../Lecture Notes/Review-for-test-2.html)

* In class **Exam 02** --- Thursday (Allowed to use the `cheat sheet`)




<!--
* [Goodness-Of-Fit](../Handouts/ChiGOF.html)

* Start _Inference for Categorical Data_ [(DataCamp)](https://www.datacamp.com/) --- Due Apr 12

* [In class Examples](../Rmarkdown/InClassNotes.html)
-->


* In class **quiz 09** --- Thursday (last 20 min of class)

## Week 14: (Apr 13--17) {-}

* [Exam 2 grades (Distribution)](../Exams/GradesExam2.html)

* Read Chapter 8 of MD

* Read Chapter 4 of MSWR

* [Lecture: Sampling Distributions](../Lecture Notes/Ch-4_MSWR_Notes.html)

* [**Lecture Recording (Ch 4 0f MSWR --- Part 2)** -- 04/14](https://appstate.zoom.us/rec/share/zu8oIIjAz0pJG5Xk71OEapE7Gr_aX6a80SdM_vZbzUt8qe1gKXdSx-sRpler-1vE)

* [**Lecture Recording (Ch 4 0f MSWR --- Part 3)** -- 04/16](https://appstate.zoom.us/rec/share/-edXKrzg0VtIRJHdzEqDWZYlLNXjeaa81HAc-fIEnUrtKltOQXxuoE2ypyJWtEXo)




* [Homework 4: Chapter 4 of MSWR](../Homework/Sampling-Distributions-HW.html)



<!--
* Read Chapter 5 of MSWR

* [Chapter 5 notes](../Notes/Children/BootStrap2.html)

* [Misc RMarkdown Examples](../Rmarkdown/MiscRmarkdown.html)

-->

* In class **quiz 10** --- Thursday (last 20 min of class)





## Week 15: (Apr 20--24) {-}

* [Lecture: Sampling Distributions](../Lecture Notes/Ch-4_MSWR_Notes.html)

* [**Lecture Recording (Ch 4 0f MSWR --- Part 3)** -- 04/16](https://appstate.zoom.us/rec/share/--N-AJjTp0hJTpHptk_8f5Q-HaXpT6a823MY_fJczkpytgMVokGIAqECV2Mt2bRf)

* [Homework 4: Chapter 4 of MSWR](../Homework/Sampling-Distributions-HW.html)


* [Lecture: Confidence Intervals: The Bootstrap](../Lecture Notes/Ch-5_MSWR_Notes.html1)

<!--
```{block, week13optional, type='rmdoptional'}
####  {-}

* Complete the problems in the [R Markdown file](https://raw.githubusercontent.com/alanarnholt/STT3850/gh-pages/Homework/Chapter5HWK.Rmd) and publish your solution to [RPubs](http://rpubs.com/).
```



* Bootstrap [Example](https://stat-ata-asu.github.io/STT3851ClassRepo/Rmarkdown/TheBootstrap.html)

* Complete _Inference for Categorical Data_ [(DataCamp)](https://www.datacamp.com/) --- Due Nov 16
-->

* [Homework 5: Chapter 5 Of MSWR](../Homework/Chapter5HWK_H.html1)

* In class **quiz 11** --- Thursday (last 20 min of class)



## Week 16: (Apr 27--May 1; No class 30th) {-}

* [Lecture: Confidence Intervals: The Bootstrap](../Lecture Notes/Ch-5_MSWR_Notes.html1)

* In class **quiz 10** --- Thursday (last 20 min of class)

* [Homework 5: Chapter 5 Of MSWR](../Homework/Chapter5HWK_H.html1)

* Review for the Final

<!--
* Read Chapter 7 of MSWR

* [Chapter 7 notes](../Notes/Children/ConfidenceIntervals2.html)

```{block, week15optional, type='rmdoptional'}
#### Optional {-}
* Complete the problems in the [R Markdown file](https://raw.githubusercontent.com/alanarnholt/STT3850/gh-pages/Homework/Chapter7HWK.Rmd) and publish your solution to [RPubs](http://rpubs.com/) 
```

-->

<!--

## Week 16: (Dec 2--6; Dec 4th is Reading Day) {-}

* Review for the Final


* [Bootstrap $t$](../Rmarkdown/MoreBootstrapping.html)
-->



### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  Final exam  is TBA

```

### Datasets

* [Exam 2 data 1](../Data/poverty.txt)
* [Exam 2 data 2](../Data/iqsize.txt)
