---
title: "Tentative STT 3850 Course Schedule"
author: "Dr. Hasthika Rupasinghe"
date: 'Last compiled: `r format(Sys.time(), "%A, %B %d, %Y - %X.")`'
output:
  html_document:
    css: ../css/style.css
    highlight: textmate
    theme: yeti
---

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

### General Notes: {-}

```{block, note-text, type='rmdnote'}
1.  Please bring a notebook and pencil to every class.
2.  The texts for this course are [ModernDive: An Introduction to Statistical and Data Sciences via R](https://moderndive.com) (MD) and _Mathematical Statistics with Resampling and R_ (MSWR)
3.  Most but not all DataCamp assignments are due by 5:00 pm on a Friday (class does not meet on Friday)
```

#### Grading Rubric for Homework Assignments {-}

Field | Excellent (3) | Competent (2)  | Needs Work (1)
------|---------------|----------------|---------------
Statistical Understanding | Answers to questions demonstrate clear statistical understanding by comparing theoretical answers to simulated answers.  When hypotheses are tested, classical methods are compared and contrasted to randomization methods.  When confidence intervals are constructed, classical approaches are compared and contrasted with bootstrap procedures.  The scope of inferential conclusions made is appropriate for the sampling method. | Theoretical and simulated answers are computed but no discussion is present comparing and contrasting the results.  When hypotheses are tested, results for classical and randomization methods are presented but are not compared and contrasted.  When confidence intervals are constructed, classical and bootstrap approaches are computed but the results are not compared and contrasted.  The scope of inferential conclusions made is appropriate for the sampling method. | Theoretical and simulated answers are not computed correctly.  No comparison between classical and randomization approaches is present when testing hypotheses.  When confidence intervals are constructed, there is no comparison between classical and bootstrap confidence intervals .
Graphics | Graphs for categorical data (barplot, mosaic plot, etc.) have appropriately labeled axes and titles.  Graphs for quantitative data (histograms, density plots, violin plots, etc.) have appropriately labeled axes and titles.  Multivariate graphs use appropriate legends and labels.  Computer variable names are replaced with descriptive variable names. | Appropriate graphs for the type of data are used.  Not all axes have appropriate labels or computer variable names are used in the graphs. | Inappropriate graphs are used for the type of data.  Axes are not labeled and computer variable names appear in the graphs.
Coding  | Code (primarily R) produces correct answers.  Non-standard or complex functions are commented.  Code is formatted using a consistent standard. | Code produces correct answers.  Commenting is not used with non-standard and complex functions.  No consistent code formatting is used. | Code does not produce correct answers.  Code has no comments and is not formatted.
Clarity  | Few errors of grammar and usage; any minor errors do not interfere with meaning.  Language style and word choice are highly effective and enhance meaning.  Style and word choice are appropriate for the assignment. | Some errors of grammar and usage; errors do not interfere with meaning.  Language style and word choice are, for the most part, effective and appropriate for the assignment. | Major errors of grammar and usage make meaning unclear.  Language style and word choice are ineffective and/or inappropriate.


## Week 1: (January 18 – 22) {-}


* Read chapters 1 and 2 of [MD](https://moderndive.com)

* Become familiar with the Appstate [RStudio server](https://mathr.math.appstate.edu/). You will use your Appstate user name and password to log in to the server.  You must be registered in the class to access the server.

* [Lecture: Intro to R](../Slides/IntroToR.html)

* In class **quiz 01** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/MTc9IM7HYCU4yJjIyilPfu0bq0dWlEhJc4VuuFD5gR1IQiygStRKkQMBa-ww8ZYw.Txk5KCC_28130EQ8)
    * [Thursday's class](https://appstate.zoom.us/rec/share/dTjzsmQ5A2gCSa8Ne6xHAfaRFYb195XsT-37txaUhqJ5dk2wyCqAn1SzyfGmOQzV.Yp6gK8uaCZrlh4ie)


## Week 2: (January 25 – 29) {-}

* Read chapter 2 of [MD](https://moderndive.com) --- Data Visualization via `ggplot2`

* Read [Getting used to R, RStudio, and R Markdown](https://ismayc.github.io/rbasics-book/)

* [Rmarkdown Basics](../Lecture Notes/R_Markdown_Basics.html)

* [Lecture: Week 2](../Lecture Notes/Week2_Ch3MD_students.html)

* In class **quiz 01** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/ouAMp3JtiZrEIF4otb-gG5spFJF-k23YX40BZCRfAeDMdkrfrqjK9fruLpfIQF0G.i10dd_R-HY6UagvX)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/MHiANtQDVAuyQqLVClUD4JVDsnskFXvjN2DKeu1-y5AWpSFO7dHJ313qx907Uvf3.W54A0yT7EvafZLcH)
    * [Thursday's class](https://appstate.zoom.us/rec/share/9L0-121Mwne86dgySuRUaagJoQ5csPhKjRMphSwsHoH2gmiMZ5et9MTfTbESNqAG.oNf8gKRfjqnZBkHE)


## Week 3 (February 01 – 05) {-}

* Read Chapter 2 of MSWR

* [Lecture - Chapter 2 of MSWR: Week 3](../Lecture Notes/Week4_Ch2MSWR_students.html)

* [Homework 1: Chapter 2 of MSWR](../Homework/Chapter2HWK.html) - Due Thursday the 11th

* In class **quiz 02** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/iaizUn6nwk0Yg8Gq3Ih6FyTM9l5QLiJOBjc_M3AxQTlbXUHZHzPvtaNNnknwqjBm.AalZBAFWYzH9WGIU)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/6JNPeA47hpjoXX5tL3L_SZ-6hlGsiVLWx8iqYzyUNCJxKaa2K_Mco3SdvFj7_Qok.pGzt8TEARSFIH6pg)
    * [Thursday's class](https://appstate.zoom.us/rec/share/MqjTrBtStnVdo6NIjMG7N9xnSxS31F-TLBEtE-tgWj413xE-x70u1mHKSiThIXT8.kzvrVOD_LeuJDZ4v)
    

```{block, TEST1, type='rmdnote'}
* Prepare R Markdown `cheat sheet` for Test 1 (Written Assignment #1---5% of course grade)
* Test 1 --- Feb 25
```


## Week 4: (February 08 – 12) {-}

* Read chapter 5 of [MD](https://moderndive.com) --- Data Wrangling via `dplyr`

* Read Chapter 3 of MSWR

* [Lecture: Before Chapter 3: the `for` loop in R](../Lecture Notes/Before_Ch_03_students.html)

* [Lecture: Chapter 3](../Lecture Notes/Ch_3_Notes_students.html)

<!--
 --- 

* Complete _Exploratory Data Analysis_ [(DataCamp)](https://www.datacamp.com/) --- 
-->

* In class **quiz 03** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/UGmyUH8dCYTEKNYxPSgpqqVcWuAj6OuoiADJbSOvkKUotSlTBfEXAr5mfSde2Q5Z.BkwwwApqV8ytMOby)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/XhuhZ_yYSkt6beK83cx41R5cmfe7CNvTCOKRH40rydW4CcaqNBruUA_FPllWRg1k.wo6o402snW1HVQTQ)
    * [Thursday's class](https://appstate.zoom.us/rec/share/RpnhftHqmM48Tjf1SP0_dJFPwQo3NSYWQuaXOnFYad-e1twdkiMmnWq3Pfm_2msN.bXfMBndYFED6L9FS)



## Week 5: (February 15 – 19) {-}

* Complete Chapters 1-3 of _Intermediate R_ [(DataCamp)](https://www.datacamp.com/courses/intermediate-r)

<!--
* Complete _Working with Data in the Tidyverse_ [(DataCamp)](https://www.datacamp.com/courses/working-with-data-in-the-tidyverse) --> 

* [Lecture: Chapter 3](../Lecture Notes/Ch_3_Notes_students.html)

* In class **quiz 04** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/m5dsPdOBFjj1v_JW8_8HD8P8y2jhTBQkjdIHst0B7YY7q-8aRUD18ZW9NQV-Dben.rLLGrNgEKigeIcZ6)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/Bbkyqi062s1p1AtA1nK-WXJe9D2_3H755ApDDdC1BOyn9NBGaYF4cN6Blxw6-ms.q3G4jrUl2_kmtDIW)
    * [Thursday's class](https://appstate.zoom.us/rec/share/YoYI5iruNmg3GwQ-Yr-1zhb8RArFjq5I6oD4jfq6TezX-UV9hZ1W81xxz5KvO1k.iBl2fKpNq1tzAvGQ)
    
    


```{block, week5optional, type='rmdoptional'}
#### Optional {-}
* Complete _Data Manipulation in R with `dplyr`_ [(DataCamp)](https://www.datacamp.com/)
* Complete _Working with Data in the Tidyverse_ [(DataCamp)](https://www.datacamp.com/courses/working-with-data-in-the-tidyverse)
```

## Week 6: (February 22 – 26) {-}

* [Lecture: Chapter 3](../Lecture Notes/Ch_3_Notes_students.html)

* [Homework 2: Chapter 3 of MSWR](../Homework/Chapter3HWK_H.html) --- 

* Read Chapters 5 [MD](https://moderndive.com) --- Basic Regression 

* In class **Exam 01** --- Thursday


*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/ZdIF6RPoLIUizhaRBe2rVn6AFnZcCJi98iupW7n2_KclXklN2U7DrOUQfzppRz0H.sdsnPwu8Gitq-zyz)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/k7c2VUtx0haK4f8T_Bp00IKmg60vnnzp0sFDtgvryxLur4pRLf8ioNimAUJNQQeh.F3P_SzQDf3nrZXLi)
    * [Thursday's class]() - Exam Day, No recording
    
    


## Week 7: (March 01 – 05) {-}

* [Exam 1 grades (Distribution)](../Exams/GradesExam1.html)

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* Read Chapters 6 [MD](https://moderndive.com) --- Basic Regression 

* Work on _Modeling with Data in Tidyverse_ [(DataCamp)](https://www.datacamp.com/) --- Optional

* In class **quiz 06** --- Thursday (last 20 min of class)

```{block, week7optional, type='rmdoptional'}
#### Optional {-}
* Skim Chapter 9 of MSWR
```

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/ELYy8Tg8GI6BVLLPeA_7UYKdTRgDVJxYbVJ1CUqRyTaT9WOTTosAoxtnzXO7PXs.YoBNxgV5K55CjhTr)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/3MHnGilcSPVxc72J00OO3cIy9KxumeGMivfB9yiEWs1X2cYRVcQ2O23vrjXVfiWg.LVodoXhxErCVWxVT)
    * [Thursday's class](https://appstate.zoom.us/rec/share/8gizWLMzGyqcsBZWb1p0aTc9P3AWoGv2uIpwnXL2SL6vvxeJCPxdjrp0VCY_Avc.BrO2keggv84eC3bf)
    
    



## Week 8: (March 08 – 12) {-}

* Read Chapters 6 of [MD](https://moderndive.com) --- Multiple Regression

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

```{block, week8optional, type='rmdoptional'}
#### Optional {-}
* Complete _Modeling with Data in Tidyverse_ [(DataCamp)](https://www.datacamp.com/)
```

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/YithbOVZUGc8n816A7LVdL03xas0ZoQkXJ21vmaOBz6xAA9fbsJgTiDGXwQKTs83.ZLGk75VszYREHFVp)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/5snIG6nIpPXAXid_fICFcO9kknlmzB9FIxGmHJ9PO2gocIicPaLsGRIZ4rEN3WiJ.vzflGNlV2dTYT_CE)
    * [Thursday's class](https://appstate.zoom.us/rec/share/St88qFMOgsNV_uMuil2lGSHqGMgSGOOGVPjTJLW2hhNupAYFEW7tJzipUNrrQZE.HlQ7KLaKQmF6zsY6)




## Week 09: (March 15 – 19) {-}

* [Lecture: Chapter 5 of MD](../Lecture Notes/Ch-6_MD_Notes.html)

* [Homework 3: Chapter 5 of MD HW](../Homework/Chapter6_Of_MD_HWK_H.pdf) 

* [OJUICE dataframe for homework 3](../Homework/data/OJUICE.Rdata) 

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/qxmRzz4iTWjGfugXF-8xqGn7Rn8EM9Md84Hyh4JCo_UJaSek6KQG_YJb98ZKNBE2.UQXeRaLLgV1XGnyE)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/oT3gt795hbfdcpmvoUna3eqfQii2eAVw1LZhJmu-ecOLWNjsJtWDMaisoNmkMhFP.pNXLFDhOGda2pUFa)



## Week 10: (March 22 – 26) {-}

* [gapminder tools](https://www.gapminder.org/tools/#$chart-type=bubbles)

* [An interesting video](https://www.youtube.com/watch?v=jbkSRLYSojo)

* Start preparing R Markdown `cheat sheet` for Test 2

```{block, TEST2, type='rmdnote'}
* Prepare R Markdown `info sheet` for Test 2...

```

* [Lecture: Chapter 6 of MD](../Lecture Notes/Ch-7_MD_Notes.html)

* In class **quiz 07** --- Thursday (last 20 min of class)


*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/QrXRmSI-ly1IpbzK0N4KGvVbPFAxh3LJXYpqI-Po_v0RQzf8zseDtpCvuOk1px8.rtb3qb1TjjyfKqfS)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/OT1oBJF_WlU50C5llKV0RHRmcX81emtQS8enkRvBR0g79p8mkP9xcX6nF8wj6QIp.MjIptoHOjUt0Msgn)
    * [Thursday's class](https://appstate.zoom.us/rec/share/v29z66H3HPcF9_IObYxIMhGbRrJBcZRnJkA1xKR-mMdkf54gf-vHecFiNjRMGb2y.mGMUe2xIUfEds_WJ)



## Week 11: (March 29 – April 02) {-}

* [Lecture: Chapter 6 of MD](../Lecture Notes/Ch-7_MD_Notes.html)

* [Homework 4: Chapter 6 of MD HW](../Homework/Chapter7HWKnew.pdf) 
* [Homework 4: Chapter 6 of MD HW txt file](../Homework/HW4_ONLINE.txt) 


* [Multiple Linear Regression mini-project](../Lecture Notes/MLR_Project.html)

* [`EXECSAL2.txt` dataframe for the mini-project](../Lecture Notes/EXECSAL2.txt) 

*  **Lecture Recordings:**

    * [Thursday's class](https://appstate.zoom.us/rec/share/djHStBjfM1eJvAr029xJmd2H-g5BpgU6g6BXdLI2n08FintGYqwuoM7rPwRTBzT8.wl5jO4llfg53snNv)
    




## Week 12: (April 05 – 09) {-}


* [Exam 2 review](../Lecture Notes/Review-for-test-2.html)

* In class **Exam 02** --- Thursday (Allowed to use the `cheat sheet`)






## Week 13: (April 12 – 16) {-}


* Read Chapter 8 of MD

* Read Chapter 4 of MSWR

* [Lecture: Sampling Distributions](../Lecture Notes/Ch-4_MSWR_Notes.html)

* [Exam 2 grades (Distribution)]()

* In class **quiz 10** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/oCEXtXruSyeQqoRGXXzqfp_3XZCWEfgGwazT8xS1O5YHyjOAsy6Lubb9k3Fs5MZd.KG858KPDSV7OZ4fs)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/dWTVWjEIYyOLEFegSMcnjVfkpRwIp6d1KTyTLEvcXVIZRrmll2cQze-0RWm0kMOP.9Tk1LIJ18M7ZF6zv)
    * [Thursday's class](https://appstate.zoom.us/rec/share/aUNJzfmmYWaqvV2J_Z3oyLL00RrXkewBp_1oIcvha4I61S4g2zUkp0_xg8Rkpfuu.STnqFoR_y_m0OKlB)




## Week 14: (April 19 – 23) {-}

* [Lecture: Sampling Distributions](../Lecture Notes/Ch-4_MSWR_Notes.html)

* [Homework 5: Chapter 4 of MSWR](../Homework/Sampling-Distributions-HW.pdf)

* In class **quiz 10** --- Thursday (last 20 min of class)

*  **Lecture Recordings:**

    * [Tuesday's class](https://appstate.zoom.us/rec/share/hk-wf4wWWfpRhOoDOQxmg_BZs6w_eR6-6-A0vF2J6puadPgD8XptoKanBmyd_EUN.cVbgM0A-CKo5SClr)
    * [Wednesday's class](https://appstate.zoom.us/rec/share/GkutYesu1u_ACWZNZBbzoHexzKHNSDtQkRKXWALFhpy3SDigwrfLDDVE3qlo9jmT.3SX7siGT1dygFkI9)
    * [Thursday's class](https://appstate.zoom.us/rec/share/gIbvLC6svtsywD6P3lS12gEX7jyONRu_Ye3IEnA63KEXrMS1YqL0XZZgbSnZ6-hb.xqaLnMYFM3XdP076)
  

<!--


## Week 15: (Apr 26--Apr 28) {-}


* [**Lecture Recording (HW 5 and quiz discussion)** -- 04/28](https://appstate.zoom.us/rec/share/38xWNLD6zFtIZ4XCyE-OW6cMMMPcaaa813ceqPYOyh0SUiOZdXUJcwd_-nHgSmQt)

* [Lecture: Confidence Intervals: The Bootstrap](../Lecture Notes/Ch-5_MSWR_Notes.html)

* In class **quiz 10** --- Thursday (last 20 min of class)

* [Homework 6: Chapter 5 Of MSWR](../Homework/Chapter5HWK_H.html1)

* Review for the Final

* [Homework 6: Chapter 5 Of MSWR](../Homework/Chapter5HWK_H.html1)
-->

### Final Exam {-}

```{block, FINAL, type='rmdnote'}
*  Final exam  will be held on Thursday, May 6th from 11.00 am to 1.30 pm.

```

<!--
### Datasets

* [Exam 2 data 1](../Data/poverty.txt)
* [Exam 2 data 2](../Data/iqsize.txt)

-->

