---
title: "Exam 1 grades"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    highlight: textmate
    theme: yeti
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(ggplot2)
```

# Exam 1 grades for 8am Class.

```{r echo=FALSE}

Class1 <- c(95,96,78,76,88,90,83,85,100,100,64,70,84,81,93,96,76,88,80,74,100,72,89,89,100,89)


p <- ggplot(data = data.frame(Class1), aes(x = Class1)) + 
  geom_density(fill = "lightblue1") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class1), linetype="dotted") +
  annotate("text",x=mean(Class1)+1,y=0.01,label="Exam Average = 88",hjust=0)

ggplotly(p)

```

# Exam 1 grades for 9.30 am Class.

```{r echo=FALSE}
library(plotly)
library(ggplot2)
Class2 <- c(76,92,60,93,100,89,50,84,97,94,93,96,72,56,100,66,91,82,94,68,96,92,56,85,54,56,99,86,86,98)


p2 <- ggplot(data = data.frame(Class2), aes(x = Class2)) + 
  geom_density(fill = "gold2") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class2), linetype="dotted") +
  annotate("text",x=mean(Class2)+1,y=0.01,label="Exam Average = 87",hjust=0)

ggplotly(p2)



```


# Exam 1 grades for Both Classes combined.

```{r echo=FALSE}
library(plotly)
library(ggplot2)
Class12 <- c(95,96,78,76,88,90,83,85,100,100,64,70,84,81,93,96,76,88,80,74,100,72,89,89,100,89,76,92,60,93,100,89,50,84,97,94,93,96,72,56,100,66,91,82,94,68,96,92,56,85,54,56,99,86,86,98)


p3 <- ggplot(data = data.frame(Class12), aes(x = Class12)) + 
  geom_density(fill = "orchid3") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class12), linetype="dotted") +
  annotate("text",x=mean(Class12)+1,y=0.01,label="Exam Average = 88",hjust=0)

ggplotly(p3)



```




# STT2810 Exam 1 grades.


```{r echo=FALSE}
library(plotly)
library(ggplot2)

class2810 <- c(0.860,0.460,0.840,0.790,0.640,0.810,0.500,0.930,0.760,0.920,0.970,0.710,0.880,0.870,0.890,0.670,0.850,0.800,0.910,0.920,0.820,0.780,0.650,0.960,0.840,0.950,0.860,0.770,0.950,0.820,0.87)
Class2810 <- class2810*100

p4 <- ggplot(data = data.frame(Class2810), aes(x = Class2810)) + 
  geom_histogram(fill = "orchid3", bins = 8) + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class2810), linetype="dotted") +
  annotate("text",x=median(Class2810)+1,y=0.01,label="Exam Average = 84",hjust=0)

ggplotly(p4)



```


```{r echo=FALSE}
library(plotly)
library(ggplot2)

class2810 <- c(0.860,0.460,0.840,0.790,0.640,0.810,0.500,0.930,0.760,0.920,0.970,0.710,0.880,0.870,0.890,0.670,0.850,0.800,0.910,0.920,0.820,0.780,0.650,0.960,0.840,0.950,0.860,0.770,0.950,0.820,0.87)
Class2810 <- class2810*100

p4 <- ggplot(data = data.frame(Class2810), aes(x = Class2810)) + 
  geom_density(fill = "orchid3") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class2810), linetype="dotted") +
  annotate("text",x=median(Class2810)+1,y=0.01,label="Exam Average = 84",hjust=0)

ggplotly(p4)



```







